version: "3"

tasks:
  run:
    - go run ./main.go -f2 tests/testdata/sample.tsv

  lint:
    - golangci-lint fmt
    - golangci-lint run --enable-only tagalign,whitespace,nlreturn --fix
    - golangci-lint run

  test:
    - go test ./... -v
